global using MTKDotNetCore.Shared;
global using System.Data;
global using MTKDotNetCore.ConsoleApp;
global using Microsoft.EntityFrameworkCore;
global using MTKDotNetCore.ConsoleApp.Models;
global using Dapper;
global using System.Data.SqlClient;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;